"""
Given a list of words (without duplicates), please write a program that returns all concatenated words in the given list
 of words.
A concatenated word is defined as a string that is comprised entirely of at least two shorter words in the given array.
"""
from typing import List


def find_all_concatenated_words(words: List[str]) -> List[str]:
    """
    :param words: list of words without duplicates
    :return: all concatenated words in the list
    """

    def dfs_recurse(current_word: str) -> bool:
        """
        :param current_word: a word in words
        :return: whether current_word is a concatenated word or a word in word_list
        """
        for i in range(1, len(current_word)):
            if current_word[:i] in word_set and (current_word[i:] in word_set or dfs_recurse(current_word[i:])):
                return True

        return False

    word_set = frozenset(words)
    return list(filter(dfs_recurse, words))


test_cases = [(["cat", "cats", "catsdogcats", "dog", "dogcatsdog", "hippopotamuses", "rat", "ratcatdogcat"],
               {"catsdogcats", "dogcatsdog", "ratcatdogcat"}),
              (["cat", "dog", "catdog"], {"catdog", }),
              (["rfkqyuqfjkx", "", "vnrtysfrzrmzl", "gfve", "qfpd", "lqdqrrcrwdnxeuo", "q", "klaitgdphcspij", "hbsfyfv",
                "adzpbfudkklrw", "aozmixr", "ife", "feclhbvfuk", "yeqfqojwtw", "sileeztxwjl", "ngbqqmbxqcqp", "khhqr",
                "dwfcayssyoqc", "omwufbdfxu", "zhift", "kczvhsybloet", "crfhpxprbsshsjxd", "ilebxwbcto", "yaxzfbjbkrxi",
                "imqpzwmshlpj", "ta", "hbuxhwadlpto", "eziwkmg", "ovqzgdixrpddzp", "c", "wnqwqecyjyib", "jy",
                "mjfqwltvzk", "tpvo", "phckcyufdqml", "lim", "lfz", "tgygdt", "nhcvpf", "fbrpzlk", "shwywshtdgmb",
                "bkkxcvg", "monmwvytby", "nuqhmfj", "qtg", "cwkuzyamnerp", "fmwevhwlezo", "ye", "hbrcewjxvcezi", "tiq",
                "tfsrptug", "iznorvonzjfea", "gama", "apwlmbzit", "s", "hzkosvn", "nberblt", "kggdgpljfisylt", "mf",
                "h", "bljvkypcflsaqe", "cijcyrgmqirz", "iaxakholawoydvch", "e", "gttxwpuk", "jf", "xbrtspfttota",
                "sngqvoijxuv", "bztvaal", "zxbshnrvbykjql", "zz", "mlvyoshiktodnsjj", "qplci", "lzqrxl", "qxru",
                "ygjtyzleizme", "inx", "lwhhjwsl", "endjvxjyghrveu", "phknqtsdtwxcktmw", "wsdthzmlmbhjkm", "u",
                "pbqurqfxgqlojmws", "mowsjvpvhznbsi", "hdkbdxqg", "ge", "pzchrgef", "ukmcowoe", "nwhpiid", "xdnnl", "n",
                "yjyssbsoc", "cdzcuunkrf", "uvouaghhcyvmlk", "aajpfpyljt", "jpyntsefxi", "wjute", "y", "pbcnmhf",
                "qmmidmvkn", "xmywegmtuno", "vuzygv", "uxtrdsdfzfssmel", "odjgdgzfmrazvnd", "a", "rdkugsbdpawxi", "ivd",
                "bbqeonycaegxfj", "lrfkraoheucsvpi", "eqrswgkaaaohxx", "hqjtkqaqh", "berbpmglbjipnuj", "wogwczlkyrde",
                "aqufowbig", "snjniegvdvotu", "ocedkt", "bbufnxorixibbd", "rzuqsyr", "qghoy", "evcuanuujszitaoa", "wsx",
                "glafbwzdd", "znrvjqeyqi", "npitruijvyllsi", "objltu", "ryp", "nvybsfrxtlfmp", "id", "zoolzslgd",
                "owijatklvjzscizr", "upmsoxftumyxifyu", "xucubv", "fctkqlroq", "zjv", "wzi", "ppvs", "mflvioemycnphfjt",
                "nwedtubynsb", "repgcx", "gsfomhvpmy", "kdohe", "tyycsibbeaxn", "wjkfvabn", "llkmagl", "thkglauzgkeuly",
                "paeurdvexqlw", "akdt", "ihmfrj", "janxk", "rqdll", "cyhbsuxnlftmjc", "yybwsjmajbwtuhkk", "ovytgaufpjl",
                "iwbnzhybsx", "mumbh", "jqmdabmyu", "br", "lwstjkoxbczkj", "vhsgzvwiixxaob", "fso", "qnebmfl",
                "ooetjiz", "lq", "msxphqdgz", "mqhoggvrvjqrp", "xbhkkfg", "zxjegsyovdrmw", "jav", "mshoj", "ax",
                "biztkfomz", "hujdmcyxdqteqja", "gqgsomonv", "reqqzzpw", "lihdnvud", "lznfhbaokxvce", "fhxbldylqqewdnj",
                "rlbskqgfvn", "lfvobeyolyy", "v", "iwh", "fpbuiujlolnjl", "gvwxljbo", "ypaotdzjxxrsc", "mwrvel",
                "umzpnoiei", "ogwilaswn", "yw", "egdgye", "hsrznlzrf", "mwdgxaigmxpy", "yaqgault", "dtlg",
                "cyvfiykmkllf", "zxqyhvizqmamj", "lvvgoifltzywueyp", "abinmy", "ppzaecvmx", "qsmzc", "iddymnl",
                "uskihek", "evxtehxtbthq", "jvtfzddlgch", "czohpyewf", "ufzazyxtqxcu", "brxpfymuvfvs", "xrrcfuusicc",
                "aqhlswbzievij", "rv", "udvmara", "upityz", "fecd", "suxteeitxtg", "dfuydrtbfypbn", "cypqodxr",
                "wikfuxwjht", "jrliuaifpp", "vkmxys", "wvpfyfpkvgthq", "rmajxis", "jncxgviyu", "av", "nmhskodmidaj",
                "lkfrimprrhen", "uip", "hstyopbvuiqc", "p", "vwduwmjpblqo", "fnxwgqtvwztje", "xwnbcuggl",
                "iehimvoymyjasin", "spsqiu", "flhyfac", "mqrbq", "pstsxhplrrmbeddv", "hnegtuxx", "alsyxezjwtlwmxv",
                "jtxytykkcku", "bhhlovgcx", "xhhivxnutkx", "had", "aysulvk", "m", "anhsyxli", "jdkgfc", "potn",
                "lcibpxkidmwexp", "gwoxjicdkv", "tltienw", "ngiutnuqbzi", "o", "tzlyb", "vumnwehj", "os", "np", "lhv",
                "uzvgyeette", "ipfvr", "lpprjjalchhhcmh", "k", "pciulccqssaqgd", "tp", "dmzdzveslyjad", "wtsbhgkd",
                "eouxbldsxzm", "vhtonlampljgzyve", "xhnlcrldtfthul", "xhflc", "upgei", "rlaks", "yfqvnvtnqspyjbxr",
                "phouoyhvls", "voibuvbhhjcdflvl", "rgorfbjrofokggaf", "dqhqats", "zchpicyuawpovm", "yzwfor", "koat",
                "pybf", "fhdzsbiyjld", "gznfnqydisn", "xz", "po", "tcjup", "wygsnxk", "kqlima", "fgxnuohrnhg",
                "publurhztntgmimc", "zuufzphd", "iucrmmmjqtcey", "wnnbq", "rghzyz", "ukjqsjbmp", "mdtrgv",
                "vyeikgjdnml", "kxwldnmi", "apzuhsbssaxj", "tkbkoljyodlipof", "nkq", "ktwtj", "vgmkgjwle", "t", "agylw",
                "vomtuy", "jbtvitkqn", "vtdxwrclpspcn", "rdrls", "yxfeoh", "upj", "myctacn", "fdnor", "ahqghzhoqprgkym",
                "phiuvdv", "jp", "fdgpouzjwbq", "hqoyefmugjvewhxu", "qfzwuwe", "fnsbijkeepyxry", "oja", "qthkcij",
                "zpmqfbmnr", "ybaibmzonzqlnmd", "svo", "gjftyfehik", "jfrfgznuaytvaegm", "aljhrx", "odjq",
                "ogwaxrssjxgvnka", "zaqswwofedxj", "lugpktauixp", "dc", "odknlbvxrs", "jeobu", "vqythyvzxbcgrlbg",
                "hwc", "erpbaxq", "ujxcxck", "rrklkb", "wlrwyuy", "zmg", "yyhga", "xwdbycdu", "htedgvsrhchox", "wr",
                "suhesetv", "jonqwhkwezjvjgg", "sqqyrxtjkcalswq", "hvyimhe", "pjzdkmoue", "zbphmgoxq",
                "lbdlcumdgixjbcq", "ztzdjqmadthtdmv", "qcagsyqggcf", "if", "jpjxcjyi", "chyicqibxdgkqtg", "iwpdklhum",
                "wljmg", "micmun", "npdbamofynykqv", "ijsnfkpfy", "lmq", "oyjmeqvhcrvgm", "mqopusqktdthpvz", "fz", "r",
                "qbsqtipq", "nxtsnason", "xbpipyhh", "topsuqomfjrd", "islif", "gbndakaq", "bwnkxnwpzeoohlx", "hrtbfnq",
                "fguvomeepxoffg", "mat", "dzfpfnwbfuj", "onlvy", "cwcchvsasdylb", "rxfcztzqopdi", "ybrhodjn", "oqkijy",
                "ncvrjo", "dphbfaal", "xgtpdtkz", "sebevsopjvciwljf", "rcumyacqdapwczen", "mabkapuoud",
                "pbozezeygljfftvy", "bvazmzbndl", "vl", "qiaixdtbhqvlzd", "ffjfb", "svthrfmkoxbho", "cvet",
                "ucgqyvopafyttrh", "lbgihet", "naiqyufxffdw", "vruh", "uz", "ukffmudygjavem", "dccamymhp", "wofwgjkykm",
                "fbuujzxhln", "kmm", "lzandlltowjpwsal", "fapfvrmezbsjxs", "wiw", "sc", "soqlh", "hzaplclkwl",
                "gcdqbcdwbwa", "gadgt", "pgowefka", "juffuguqepwnfh", "nbuinl", "cpdxf", "sox", "fq", "lfnrhgsxkhx",
                "xrcorfygjxpi", "mwtqjwbhgh", "loc", "fkglorkkvx", "nlzdhucvayrz", "azefobxutitrf", "rlrstkcbtikklmh",
                "ggk", "sbphcejuylh", "nraoenhd", "zngyodiqlchxyycx", "rrbhfwohfv", "krzolrglgn", "cpjesdzy", "yoifoyg",
                "hqqevqjugi", "ahmv", "xgaujnyclcjq", "evhyfnlohavrj", "byyvhgh", "hyw", "kedhvwy", "ysljsqminajfipds",
                "rglnpxfqwu", "cibpynkxg", "su", "mbntqrlwyampdg", "nig", "ldhlhqdyjcfhu", "jfymrbafmyoc",
                "tyjmnhlfnrtz", "dlazixtlxyvm", "fbiguhsfuqo", "rhymsno", "rkbdlchs", "ocbbwwd", "astaiamnepwkya",
                "mplirup", "edkxjq", "g", "exlwulswtvot", "tlnc", "vnrrzerz", "ygeraoozbtt", "yyifkin", "eo", "ua",
                "qgztvqdolf", "rlzddjzcshvd", "khxkdxflwxme", "kk", "zylbhoaac", "cw", "iizic", "gcdxstpz", "kjwdqeg",
                "earjrncmmkdel", "kbesuhquepj", "nrzbllldgdmyrpgl", "hllwnqozf", "djpchowhwevbqvjj", "zsmhylnjpktb",
                "pxnktxkm", "fxwiaqqb", "qjwufmwresfsfaok", "aa", "d", "iobioqm", "svjgzk", "khbzp", "euexyudhrioi",
                "yqsj", "ngrwqpoh", "rwuvd", "eruffmlg", "bxzovyew", "faz", "pmvfvyguqdi", "jlxnoixsy", "hyfrdngjf",
                "ly", "eibcapetpmeaid", "tpnwwiif", "pfgsp", "kvhhwkzvtvlhhb", "pjxurgqbtldims", "rncplkeweoirje",
                "akyprzzphew", "wyvfpjyglzrmhfqp", "ubheeqt", "rmbxlcmn", "taqakgim", "apsbu", "khwnykughmwrlk",
                "vtdlzwpbhcsbvjno", "tffmjggrmyil", "schgwrrzt", "mvndmua", "nlwpw", "glvbtkegzjs", "piwllpgnlpcnezqs",
                "xkelind", "urtxsezrwz", "zechoc", "vfaimxrqnyiq", "ybugjsblhzfravzn", "btgcpqwovwp", "zgxgodlhmix",
                "sfzdknoxzassc", "wgzvqkxuqrsqxs", "dwneyqisozq", "fg", "vhfsf", "uspujvqhydw", "eadosqafyxbmzgr",
                "tyff", "blolplosqnfcwx", "uwkl", "puenodlvotb", "iizudxqjvfnky", "cjcywjkfvukvveq", "jrxd", "igwb",
                "dftdyelydzyummmt", "uvfmaicednym", "oai", "higfkfavgeemcgo", "naefganqo", "iqebfibigljbc",
                "ulicojzjfrc", "igxprunj", "cymbrl", "fqmwciqtynca", "zjyagi", "mzuejrttefhdwqc", "zyiurxvf",
                "wrjxffzbjexsh", "wrxw", "mhrbdxjwi", "htknfa", "wfrvxqdkhbwwef", "vqsghhhutdget", "cwupzrts", "hbjnb",
                "wpccoa", "nx", "howbzhaoscgyk", "bilt", "wqqatye", "zceuuwg", "jxzon", "kkfj", "bwsezd",
                "ifdegsyjtswselk", "xweimxlnzoh", "tqthlftjblnpht", "ww", "ss", "b", "jmruuqscwjp", "nxbk", "wd",
                "cqkrtbxgzg", "xhppcjnq", "cfq", "tkkolzcfi", "wblxki", "ijeglxsvc", "kcqjjwcwuhvzydm",
                "gubqavlqffhrzz", "hiwxrgftittd", "caybc", "ncsyjlzlxyyklc", "poxcgnexmaajzuha", "dhaccuualacyl",
                "mtkewbprs", "oncggqvr", "sqqoffmwkplsgbrp", "ioajuppvqluhbdet", "dzwwzaelmo", "afumtqugec",
                "wglucmugwqi", "zveswrjevfz", "nxlbkak", "pzcejvxzeoybb", "fd", "vewj", "ivws", "zjhudtpqsfc",
                "zcmukotirrxx", "zksmx", "umofzhhowyftz", "zbotrokaxaryxlk", "ueolqk", "dxmzhoq", "zvu", "cjl",
                "esfmqgvxwfy", "npbep", "vbgjtbv", "poeugoqynkbfiv", "fewjjscjrei", "yqssxzsydgllfzmo",
                "urxkwcypctjkabi", "wqtldwhjouas", "tovdtkr", "onzgeyddkqwuhnim", "ffxviyvsktqrfa", "qujhd", "pvcz",
                "hiyjlkxmeplnrvxg", "hdykehkefp", "vepcxhozpjxtreyn", "liguhuxudbnh", "f", "ordxzm", "klgohcmmbukz",
                "yrmooliaobbnlap", "dutnbetocxylcey", "ywdsjegd", "cr", "blbxhjsgcuoxmqft", "ngzdc", "srfyjjumcbxole",
                "dazwzwtdjoyuqeqj", "xazjarqgfm", "fxyfqbeoktcc", "qrsjchxp", "iltaqzawhgu", "sgenjcfxr", "yfikp",
                "dvwhbyumthkiktb", "walsx", "jyajrkcvysicisab", "brdeumb", "tviihjwxdcz", "dnrrgmem", "ydgxlrjzucxyid",
                "cdvdpvjlagwmg", "ngnpxjkxims", "gvyhnchlimsxc", "w", "jtizpezjl", "qe", "rjzv", "vhnqvi", "qm",
                "iedzqswrsnfmnn", "lt", "utqfcqyrrwm", "wtelvsqrru", "fjwrhjcrtbcytn", "qmqxceuohpiffaq",
                "rmoybqjjgdyo", "pmxttqftypfexlv", "tg", "qa", "iqbqjlnpbf", "kgaynkddbzllecd", "tccvslp",
                "curkxfoimnw", "fvnyqkzlheruxr", "iiygnzfov", "coqs", "oa", "eiu", "vzemmxtklis", "lxu", "nrwsjaxzwmh",
                "tdayz", "oxbbemejgosgcynf", "ykbcn", "hesvnctfvdsp", "ku", "rjhykpadahbhj", "at", "sxlngbtxmqr",
                "wqrom", "qzyabzrco", "rbbyklndcqdj", "cnsmgmwmpbgjq", "krvnaf", "qrwfajnfahyqocdb", "fnlaozmff",
                "vmoymbmytjvfcgt", "cijyy", "jdgwjbztl", "swmalgbgpaplqgz", "hfl", "typttkrpfvx", "tkzpzrscwbx",
                "bwfqqvjcukjbsg", "nxqmxr", "x", "eyavnz", "il", "dhthp", "eyelg", "npsoqsw", "reogbmveofvusdsx",
                "jvdrjkhxkq", "qzjbrpljwuzpl", "czqeevvbvcwh", "vzuszqvhlmapty", "yu", "yldwwgezlqur",
                "vorxwgdtgjilgydq", "pknt", "bgihl", "ckorgrm", "ixylxjmlfv", "bpoaboylced", "zea", "igfagitkrext",
                "ipvqq", "dmoerc", "oqxbypihdv", "dtjrrkxro", "rexuhucxpi", "bvmuyarjwqpcoywa", "qwdmfpwvamisns",
                "bhopoqdsref", "tmnm", "cre", "ktrniqwoofoeenbz", "vlrfcsftapyujmw", "updqikocrdyex", "bcxw", "eaum",
                "oklsqebuzeziisw", "fzgyhvnwjcns", "dybjywyaodsyw", "lmu", "eocfru", "ztlbggsuzctoc", "ilfzpszgrgj",
                "imqypqo", "fump", "sjvmsbrcfwretbie", "oxpmplpcg", "wmqigymr", "qevdyd", "gmuyytguexnyc",
                "hwialkbjgzc", "lmg", "gijjy", "lplrsxznfkoklxlv", "xrbasbznvxas", "twn", "bhqultkyfq", "saeq", "xbuw",
                "zd", "kng", "uoay", "kfykd", "armuwp", "gtghfxf", "gpucqwbihemixqmy", "jedyedimaa", "pbdrx",
                "toxmxzimgfao", "zlteob", "adoshnx", "ufgmypupei", "rqyex", "ljhqsaneicvaerqx", "ng", "sid",
                "zagpiuiia", "re", "oadojxmvgqgdodw", "jszyeruwnupqgmy", "jxigaskpj", "zpsbhgokwtfcisj", "vep",
                "ebwrcpafxzhb", "gjykhz", "mfomgxjphcscuxj", "iwbdvusywqlsc", "opvrnx", "mkgiwfvqfkotpdz",
                "inpobubzbvstk", "vubuucilxyh", "bci", "dibmye", "rlcnvnuuqfvhw", "oorbyyiigppuft", "swpksfdxicemjbf",
                "goabwrqdoudf", "yjutkeqakoarru", "wuznnlyd", "vfelxvtggkkk", "mxlwbkbklbwfsvr", "advraqovan", "smkln",
                "jxxvzdjlpyurxpj", "ssebtpznwoytjefo", "dynaiukctgrzjx", "irzosjuncvh", "hcnhhrajahitn",
                "vwtifcoqepqyzwya", "kddxywvgqxo", "syxngevs", "batvzmziq", "mjewiyo", "pzsupxoflq", "byzhtvvpj",
                "cqnlvlzr", "akvmxzbaei", "mwo", "vg", "ekfkuajjogbxhjii", "isdbplotyak", "jvkmxhtmyznha",
                "lqjnqzrwrmgt", "mbbhfli", "bpeohsufree", "ajrcsfogh", "lucidbnlysamvy", "tutjdfnvhahxy", "urbrmmadea",
                "hghv", "acnjx", "athltizloasimp", "gu", "rjfozvgmdakdhao", "iephs", "uztnpqhdl", "rfuyp",
                "crcszmgplszwfn", "zihegt", "xbspa", "cjbmsamjyqqrasz", "ghzlgnfoas", "ljxl", "cnumquohlcgt", "jm",
                "mfccj", "hfedli", "vtpieworwhyiucs", "tdtuquartspkotm", "pnkeluekvelj", "ugrloq", "zljmwt",
                "fkyvqguqq", "tpjidglpxqfxv", "l", "tvvimvroz", "yy", "opwyfovdz", "pwlumocnyuoume", "vjqpzkcfc",
                "ihicd", "dtttiixlhpikbv", "goblttgvmndkqgg", "gwsibcqahmyyeagk", "prtvoju", "lcblwidhjpu", "kbu",
                "pey", "gkzrpc", "bqajopjjlfthe", "bc", "lqs", "zkndgojnjnxqsoqi", "zyesldujjlp", "drswybwlfyzph",
                "xzluwbtmoxokk", "bedrqfui", "opajzeahv", "lehdfnr", "mnlpimduzgmwszc", "velbhj", "miwdn", "wruqc",
                "kscfodjxg", "wcbm"],
               {'ugrloq', 'rqdll', 'gama', 'aa', 'lcblwidhjpu', 'ye', 'advraqovan', 'dhaccuualacyl', 'mtkewbprs',
                'fguvomeepxoffg', 'tlnc', 'cvet', 'had', 'yxfeoh', 'wcbm', 'xwnbcuggl', 'rfuyp', 'ku', 'egdgye', 'lmg',
                'xzluwbtmoxokk', 'ss', 'cr', 'bhhlovgcx', 'brdeumb', 'gttxwpuk', 'pxnktxkm', 'coqs', 'phouoyhvls',
                'gtghfxf', 'dnrrgmem', 'xhflc', 'btgcpqwovwp', 'fump', 'rv', 'mxlwbkbklbwfsvr', 'ocedkt', 'qnebmfl',
                'akdt', 'erpbaxq', 'tdtuquartspkotm', 'ogwilaswn', 'lplrsxznfkoklxlv', 'ngrwqpoh', 'nlwpw', 'lxu',
                'myctacn', 'nraoenhd', 'yaqgault', 'dmoerc', 'kqlima', 'tyff', 'qfpd', 'xmywegmtuno', 'vep',
                'rlcnvnuuqfvhw', 'yqssxzsydgllfzmo', 'ykbcn', 'tfsrptug', 'dc', 'hbsfyfv', 'tpvo', 'xhnlcrldtfthul',
                'kedhvwy', 'reogbmveofvusdsx', 'khxkdxflwxme', 'gmuyytguexnyc', 'npsoqsw', 'sfzdknoxzassc', 'rwuvd',
                'qxru', 'esfmqgvxwfy', 'ebwrcpafxzhb', 'paeurdvexqlw', 'tgygdt', 'hyw', 'ly', 'gu', 'gsfomhvpmy',
                'bcxw', 'monmwvytby', 'nvybsfrxtlfmp', 'su', 'lfnrhgsxkhx', 'xbspa', 'jmruuqscwjp', 'npdbamofynykqv',
                'rrklkb', 'syxngevs', 'rdrls', 'rmbxlcmn', 'lhv', 'dccamymhp', 'bpoaboylced', 'bpeohsufree',
                'uztnpqhdl', 'nxlbkak', 'yu', 'khwnykughmwrlk', 'hdykehkefp', 'svthrfmkoxbho', 'eyelg', 'ng',
                'bxzovyew', 'bilt', 'nwedtubynsb', 'ryp', 'tg', 'udvmara', 'eqrswgkaaaohxx', 'pbqurqfxgqlojmws',
                'ocbbwwd', 'lucidbnlysamvy', 'bc', 'armuwp', 'agylw', 'eo', 'ax', 'wtsbhgkd', 'pfgsp', 'nberblt',
                'blolplosqnfcwx', 'cw', 'shwywshtdgmb', 'wvpfyfpkvgthq', 'yyhga', 'kng', 'mwrvel', 'exlwulswtvot',
                'ckorgrm', 'goblttgvmndkqgg', 'yjyssbsoc', 'gbndakaq', 'kmm', 'hdkbdxqg', 'vruh', 'fso',
                'pmxttqftypfexlv', 'naefganqo', 'wpccoa', 'adoshnx', 'dtlg', 'vubuucilxyh', 'byyvhgh', 'soqlh', 'fg',
                'kfykd', 'suhesetv', 'lmq', 'aysulvk', 'walsx', 'puenodlvotb', 'dphbfaal', 'ppvs', 'av', 'fctkqlroq',
                'kbu', 'brxpfymuvfvs', 'cwcchvsasdylb', 'vg', 'sox', 'lqdqrrcrwdnxeuo', 'fq', 'ta', 'lfvobeyolyy',
                'feclhbvfuk', 'vkmxys', 'onlvy', 'mdtrgv', 'smkln', 'utqfcqyrrwm', 'vhfsf', 'ngzdc', 'wr',
                'pstsxhplrrmbeddv', 'sqqoffmwkplsgbrp', 'xdnnl', 'twn', 'glafbwzdd', 'fd', 'wuznnlyd', 'ilebxwbcto',
                'nkq', 'potn', 'nxqmxr', 'vl', 'svo', 'repgcx', 'tovdtkr', 'ge', 'dwfcayssyoqc', 'uoay', 'vomtuy',
                'eaum', 'po', 'llkmagl', 'uxtrdsdfzfssmel', 'uvouaghhcyvmlk', 'oncggqvr', 'goabwrqdoudf', 'afumtqugec',
                'hfl', 'uwkl', 'wfrvxqdkhbwwef', 'akyprzzphew', 'jfymrbafmyoc', 'ww', 'hbuxhwadlpto', 'tccvslp',
                'opvrnx', 'krvnaf', 'caybc', 'omwufbdfxu', 'ife', 'cnumquohlcgt', 'rlaks', 'ngbqqmbxqcqp', 'vuzygv',
                'wd', 'np', 'hghv', 'hnegtuxx', 'sid', 'mbntqrlwyampdg', 'sxlngbtxmqr', 'fkglorkkvx', 'iddymnl',
                'qmmidmvkn', 'upmsoxftumyxifyu', 'nhcvpf', 'eocfru', 'xbuw', 'gcdqbcdwbwa', 'wlrwyuy', 'at',
                'uzvgyeette', 'bhopoqdsref', 'os', 'gfve', 'fdnor', 'pybf', 'wtelvsqrru', 'pwlumocnyuoume', 'cypqodxr',
                'qghoy', 'typttkrpfvx', 'flhyfac', 'qfzwuwe', 'qm', 'pey', 'cymbrl', 'htknfa', 'nxbk', 'br', 'koat',
                'wnnbq', 'npbep', 'qtg', 'ordxzm', 'gqgsomonv', 'rlbskqgfvn', 'mumbh', 'nx', 'dutnbetocxylcey',
                'dqhqats', 'rkbdlchs', 'bwsezd', 'odknlbvxrs', 'tmnm', 'dybjywyaodsyw', 'phknqtsdtwxcktmw',
                'gubqavlqffhrzz', 'fxyfqbeoktcc', 'pknt', 'ukmcowoe', 'hwc', 'ggk', 'xwdbycdu', 'oyjmeqvhcrvgm', 'lmu',
                'xbhkkfg', 'hrtbfnq', 'pgowefka', 'cpdxf', 'thkglauzgkeuly', 'wljmg', 'pbdrx', 'lfz', 'rrbhfwohfv',
                'wqqatye', 'mat', 'wrxw', 'wqrom', 'khhqr', 'kddxywvgqxo', 'bkkxcvg', 'ucgqyvopafyttrh', 'xucubv',
                'evxtehxtbthq', 'lehdfnr', 'vlrfcsftapyujmw', 'kk', 'cfq', 'htedgvsrhchox', 'eruffmlg', 'phckcyufdqml',
                'ubheeqt', 'cre', 'nxtsnason', 'rhymsno', 'oa', 'saeq', 'yy', 'oxpmplpcg', 'qa', 'pbcnmhf', 'ahmv',
                'dhthp', 'fgxnuohrnhg', 'rqyex', 'loc', 'gvyhnchlimsxc', 're', 'mwo', 'dfuydrtbfypbn', 'rglnpxfqwu',
                'kdohe', 'cwkuzyamnerp', 'lqs', 'wsx', 'mabkapuoud', 'qevdyd', 'ukffmudygjavem', 'sc', 'fkyvqguqq',
                'vwduwmjpblqo', 'yoifoyg', 'mf', 'wruqc', 'gadgt', 'qcagsyqggcf', 'fecd', 'qe', 'ua', 'ueolqk',
                'eouxbldsxzm', 'wygsnxk', 'qmqxceuohpiffaq', 'yw', 'vqsghhhutdget', 'vfelxvtggkkk', 'ffjfb',
                'urbrmmadea', 'hyfrdngjf', 'xbrtspfttota', 'mqrbq', 'vtdxwrclpspcn', 'hesvnctfvdsp', 'bhqultkyfq', 'lq',
                'lt', 'tp', 'reqqzzpw', 'apsbu', 'mvndmua'}),
              ]
for test_words, expected_output in test_cases:
    assert set(find_all_concatenated_words(test_words)) == expected_output
